import {
  LayoutDashboard,
  Film,
  Tv,
  Captions,
  Search,
  Download,
  PlayCircle,
  ListChecks,
  CalendarDays,
  Telescope,
  BarChart2,
  Bookmark,
  Clock,
  Sparkles,
  Activity,
  Bell,
} from "lucide-react";

export const NAV_ITEMS = [
  { href: "/", label: "Vue d'ensemble", icon: LayoutDashboard, primary: true },
  { href: "/watchlist", label: "Ma liste", icon: Bookmark, primary: true },
  { href: "/timeline", label: "Timeline", icon: Clock, primary: true },
  { href: "/calendar", label: "Calendrier", icon: CalendarDays, primary: true },
  { href: "/recommendations", label: "Recommandations", icon: Sparkles, primary: true },
  { href: "/discover", label: "Découverte", icon: Telescope, primary: true },
  { href: "/radarr", label: "Films · Radarr", icon: Film, primary: true },
  { href: "/sonarr", label: "Séries · Sonarr", icon: Tv, primary: true },
  { href: "/qbittorrent", label: "Téléchargements", icon: Download, primary: true },
  { href: "/notifications", label: "Notifications", icon: Bell, primary: true },
  { href: "/stats", label: "Statistiques", icon: BarChart2, primary: true },
  { href: "/bazarr", label: "Sous-titres · Bazarr", icon: Captions, primary: false },
  { href: "/jackett", label: "Indexeurs · Jackett", icon: Search, primary: false },
  { href: "/jellyfin", label: "Lecture · Jellyfin", icon: PlayCircle, primary: false },
  { href: "/jellyseerr", label: "Demandes · Jellyseerr", icon: ListChecks, primary: false },
  { href: "/health", label: "Santé système", icon: Activity, primary: false },
];
