import {
  LayoutDashboard,
  Film,
  Tv,
  Captions,
  Search,
  Download,
  PlayCircle,
  ListChecks,
  CalendarDays,
  Telescope,
  BarChart2,
  Bookmark,
  Clock,
  Sparkles,
  Activity,
  Settings,
} from "lucide-react";

export const NAV_ITEMS = [
  { href: "/", navKey: "nav.overview", icon: LayoutDashboard, primary: true },
  { href: "/watchlist", navKey: "nav.watchlist", icon: Bookmark, primary: true },
  { href: "/timeline", navKey: "nav.timeline", icon: Clock, primary: true },
  { href: "/calendar", navKey: "nav.calendar", icon: CalendarDays, primary: true },
  { href: "/recommendations", navKey: "nav.recommendations", icon: Sparkles, primary: true },
  { href: "/discover", navKey: "nav.discover", icon: Telescope, primary: true },
  { href: "/radarr", navKey: "nav.radarr", icon: Film, primary: true },
  { href: "/sonarr", navKey: "nav.sonarr", icon: Tv, primary: true },
  { href: "/qbittorrent", navKey: "nav.qbittorrent", icon: Download, primary: true },
  { href: "/parametres", navKey: "nav.settings", icon: Settings, primary: true },
  { href: "/stats", navKey: "nav.stats", icon: BarChart2, primary: true },
  { href: "/bazarr", navKey: "nav.bazarr", icon: Captions, primary: false },
  { href: "/jackett", navKey: "nav.jackett", icon: Search, primary: false },
  { href: "/jellyfin", navKey: "nav.jellyfin", icon: PlayCircle, primary: false },
  { href: "/jellyseerr", navKey: "nav.jellyseerr", icon: ListChecks, primary: false },
  { href: "/health", navKey: "nav.health", icon: Activity, primary: false },
];
